version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres-frotamais
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: frotamais
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
